title: Chi Señires
tagline: UX designer and web developer from the Philippines
description: Chi is a UX Designer and Front-End Web Developer from the Philippines with over 4 years of experience.
url: https://chisenires.ph

# Google Analytics
# google_analytics: UA-115634204-2